export class AppConstant {
    public static flightData = [
      {
        'origin': 'Amritsar',
        'destination': 'Delhi',
        'status': 'AMR > DEL',
        'flightName': 'AirIndia-1006',
        'fare': 2500,
        'dueDate': '2017-10-18',
        'departureTime': '8:30 AM',
        'arrivalTime': '10:00 AM',
        'avatar': 'image1',
        'id': '906'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Delhi',
        'status': 'AMR > DEL',
        'flightName': 'AirIndia-1005',
        'fare': 2500,
        'dueDate': '2017-10-19',
        'departureTime': '8:00 AM',
        'arrivalTime': '9:30 AM',
        'avatar': 'image2',
        'id': '905'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Delhi',
        'status': 'AMR > DEL',
        'flightName': 'AirIndia-1006',
        'fare': 2500,
        'dueDate': '2017-10-19',
        'departureTime': '6:30 AM',
        'arrivalTime': '8:00 AM',
        'avatar': 'image1',
        'id': '906'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Delhi',
        'status': 'AMR > DEL',
        'flightName': 'AirIndia-1005',
        'fare': 2500,
        'dueDate': '2017-10-20',
        'departureTime': '8:00 AM',
        'arrivalTime': '9:30 AM',
        'avatar': 'image2',
        'id': '905'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Delhi',
        'status': 'AMR > DEL',
        'flightName': 'AirIndia-1006',
        'fare': 2500,
        'dueDate': '2017-10-18',
        'departureTime': '9:30 AM',
        'arrivalTime': '10:30 AM',
        'avatar': 'image1',
        'id': '906'
      },
      {
        'origin': 'Delhi',
        'destination': 'Amritsar',
        'status': 'DEL > AMR',
        'flightName': 'AirIndia-1007',
        'fare': 2800,
        'dueDate': '2017-10-18',
        'departureTime': '1:00 PM',
        'arrivalTime': '3:00 PM',
        'avatar': 'image2',
        'id': '907'
      },
      {
        'origin': 'Delhi',
        'destination': 'Amritsar',
        'status': 'DEL > AMR',
        'flightName': 'AirIndia-1008',
        'fare': 1900,
        'dueDate': '2017-10-18',
        'departureTime': '1:30 PM',
        'arrivalTime': '3:30 PM',
        'avatar': 'image1',
        'id': '908'
      },
      {
        'origin': 'Delhi',
        'destination': 'Amritsar',
        'status': 'DEL > AMR',
        'flightName': 'AirIndia-1007',
        'fare': 2800,
        'dueDate': '2017-10-19',
        'departureTime': '1:00 PM',
        'arrivalTime': '3:00 PM',
        'avatar': 'image2',
        'id': '907'
      },
      {
        'origin': 'Delhi',
        'destination': 'Amritsar',
        'status': 'DEL > AMR',
        'flightName': 'AirIndia-1008',
        'fare': 1900,
        'dueDate': '2017-10-19',
        'departureTime': '1:30 PM',
        'arrivalTime': '3:30 PM',
        'avatar': 'image1',
        'id': '908'
      },
      {
        'origin': 'Delhi',
        'destination': 'Amritsar',
        'status': 'DEL > AMR',
        'flightName': 'AirIndia-1007',
        'fare': 2800,
        'dueDate': '2017-10-20',
        'departureTime': '1:00 PM',
        'arrivalTime': '3:00 PM',
        'avatar': 'image2',
        'id': '907'
      },
      {
        'origin': 'Delhi',
        'destination': 'Amritsar',
        'status': 'DEL > AMR',
        'flightName': 'AirIndia-1008',
        'fare': 1900,
        'dueDate': '2017-10-20',
        'departureTime': '1:30 PM',
        'arrivalTime': '3:30 PM',
        'avatar': 'image1',
        'id': '908'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Pune',
        'status': 'AMR > PNQ',
        'flightName': 'AirIndia-1009',
        'fare': 4100,
        'dueDate': '2017-10-18',
        'departureTime': '2:30 PM',
        'arrivalTime': '4:30 PM',
        'avatar': 'image2',
        'id': '909'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Pune',
        'status': 'AMR > PNQ',
        'flightName': 'AirIndia-1110',
        'fare': 4900,
        'dueDate': '2017-10-18',
        'departureTime': '1:30 PM',
        'arrivalTime': '4:30 PM',
        'avatar': 'image1',
        'id': '910'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Pune',
        'status': 'AMR > PNQ',
        'flightName': 'AirIndia-1009',
        'fare': 4100,
        'dueDate': '2017-10-19',
        'departureTime': '2:30 PM',
        'arrivalTime': '4:30 PM',
        'avatar': 'image2',
        'id': '909'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Pune',
        'status': 'AMR > PNQ',
        'flightName': 'AirIndia-1110',
        'fare': 4900,
        'dueDate': '2017-10-19',
        'departureTime': '1:30 PM',
        'arrivalTime': '4:30 PM',
        'avatar': 'image1',
        'id': '910'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Pune',
        'status': 'AMR > PNQ',
        'flightName': 'AirIndia-1009',
        'fare': 4100,
        'dueDate': '2017-10-20',
        'departureTime': '2:30 PM',
        'arrivalTime': '4:30 PM',
        'avatar': 'image2',
        'id': '909'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Pune',
        'status': 'AMR > PNQ',
        'flightName': 'AirIndia-1110',
        'fare': 4900,
        'dueDate': '2017-10-20',
        'departureTime': '1:30 PM',
        'arrivalTime': '4:30 PM',
        'avatar': 'image1',
        'id': '910'
      },
      {
        'origin': 'Pune',
        'destination': 'Amritsar',
        'status': 'PNQ > AMR',
        'flightName': 'AirIndia-1111',
        'fare': 4100,
        'dueDate': '2017-10-18',
        'departureTime': '2:30 PM',
        'arrivalTime': '5:00 PM',
        'avatar': 'image2',
        'id': '911'
      },
      {
        'origin': 'Pune',
        'destination': 'Amritsar',
        'status': 'PNQ > AMR',
        'flightName': 'AirIndia-1112',
        'fare': 4200,
        'dueDate': '2017-10-18',
        'departureTime': '3:30 PM',
        'arrivalTime': '6:00 PM',
        'avatar': 'image1',
        'id': '912'
      },
      {
        'origin': 'Pune',
        'destination': 'Amritsar',
        'status': 'PNQ > AMR',
        'flightName': 'AirIndia-1111',
        'fare': 4100,
        'dueDate': '2017-10-19',
        'departureTime': '2:30 PM',
        'arrivalTime': '5:00 PM',
        'avatar': 'image2',
        'id': '911'
      },
      {
        'origin': 'Pune',
        'destination': 'Amritsar',
        'status': 'PNQ > AMR',
        'flightName': 'AirIndia-1112',
        'fare': 4200,
        'dueDate': '2017-10-19',
        'departureTime': '3:30 PM',
        'arrivalTime': '6:00 PM',
        'avatar': 'image1',
        'id': '912'
      },
      {
        'origin': 'Pune',
        'destination': 'Amritsar',
        'status': 'PNQ > AMR',
        'flightName': 'AirIndia-1111',
        'fare': 4100,
        'dueDate': '2017-10-20',
        'departureTime': '2:30 PM',
        'arrivalTime': '5:00 PM',
        'avatar': 'image2',
        'id': '911'
      },
      {
        'origin': 'Pune',
        'destination': 'Amritsar',
        'status': 'PNQ > AMR',
        'flightName': 'AirIndia-1112',
        'fare': 4200,
        'dueDate': '2017-10-20',
        'departureTime': '3:30 PM',
        'arrivalTime': '6:00 PM',
        'avatar': 'image1',
        'id': '912'
      },
      {
        'origin': 'Pune',
        'destination': 'Delhi',
        'status': 'PNQ > DEL',
        'flightName': 'AirIndia-1001',
        'fare': 3750,
        'dueDate': '2017-10-18',
        'departureTime': '10:00 AM',
        'arrivalTime': '12:00 PM',
        'avatar': 'image2',
        'id': '901'
      },
      {
        'origin': 'Pune',
        'destination': 'Delhi',
        'status': 'PNQ > DEL',
        'flightName': 'AirIndia-1002',
        'fare': 3750,
        'dueDate': '2017-10-18',
        'departureTime': '10:30 AM',
        'arrivalTime': '12:30 PM',
        'avatar': 'image1',
        'id': '902'
      },
      {
        'origin': 'Pune',
        'destination': 'Delhi',
        'status': 'PNQ > DEL',
        'flightName': 'AirIndia-1001',
        'fare': 3750,
        'dueDate': '2017-10-19',
        'departureTime': '10:00 AM',
        'arrivalTime': '12:00 PM',
        'avatar': 'image2',
        'id': '901'
      },
      {
        'origin': 'Pune',
        'destination': 'Delhi',
        'status': 'PNQ > DEL',
        'flightName': 'AirIndia-1002',
        'fare': 3750,
        'dueDate': '2017-10-19',
        'departureTime': '10:30 AM',
        'arrivalTime': '12:30 PM',
        'avatar': 'image1',
        'id': '902'
      },
      {
        'origin': 'Pune',
        'destination': 'Delhi',
        'status': 'PNQ > DEL',
        'flightName': 'AirIndia-1001',
        'fare': 3750,
        'dueDate': '2017-10-20',
        'departureTime': '10:00 AM',
        'arrivalTime': '12:00 PM',
        'avatar': 'image2',
        'id': '901'
      },
      {
        'origin': 'Pune',
        'destination': 'Delhi',
        'status': 'PNQ > DEL',
        'flightName': 'AirIndia-1002',
        'fare': 3750,
        'dueDate': '2017-10-20',
        'departureTime': '10:30 AM',
        'arrivalTime': '12:30 PM',
        'avatar': 'image1',
        'id': '902'
      },
      {
        'origin': 'Delhi',
        'destination': 'Pune',
        'status': 'DEL > PNQ',
        'flightName': 'AirIndia-1003',
        'fare': 3900,
        'dueDate': '2017-10-18',
        'departureTime': '1:00 PM',
        'arrivalTime': '3:00 PM',
        'avatar': 'image2',
        'id': '903'
      },
      {
        'origin': 'Delhi',
        'destination': 'Pune',
        'status': 'DEL > PNQ',
        'flightName': 'AirIndia-1004',
        'fare': 3900,
        'dueDate': '2017-10-18',
        'departureTime': '1:30 PM',
        'arrivalTime': '3:30 PM',
        'avatar': 'image1',
        'id': '904'
      },
      {
        'origin': 'Delhi',
        'destination': 'Pune',
        'status': 'DEL > PNQ',
        'flightName': 'AirIndia-1003',
        'fare': 3900,
        'dueDate': '2017-10-19',
        'departureTime': '1:00 PM',
        'arrivalTime': '3:00 PM',
        'avatar': 'image2',
        'id': '903'
      },
      {
        'origin': 'Delhi',
        'destination': 'Pune',
        'status': 'DEL > PNQ',
        'flightName': 'AirIndia-1004',
        'fare': 3900,
        'dueDate': '2017-10-19',
        'departureTime': '1:30 PM',
        'arrivalTime': '3:30 PM',
        'avatar': 'image1',
        'id': '904'
      },
      {
        'origin': 'Delhi',
        'destination': 'Pune',
        'status': 'DEL > PNQ',
        'flightName': 'AirIndia-1003',
        'fare': 3900,
        'dueDate': '2017-10-20',
        'departureTime': '1:00 PM',
        'arrivalTime': '3:00 PM',
        'avatar': 'image2',
        'id': '903'
      },
      {
        'origin': 'Delhi',
        'destination': 'Pune',
        'status': 'DEL > PNQ',
        'flightName': 'AirIndia-1004',
        'fare': 3900,
        'dueDate': '2017-10-20',
        'departureTime': '1:30 PM',
        'arrivalTime': '3:30 PM',
        'avatar': 'image1',
        'id': '904'
      },
      {
        'origin': 'Amritsar',
        'destination': 'Delhi',
        'status': 'AMR > DEL',
        'flightName': 'AirIndia-1005',
        'fare': 2500,
        'dueDate': '2017-10-18',
        'departureTime': '8:00 AM',
        'arrivalTime': '9:30 AM',
        'avatar': 'image2',
        'id': '905'
      }
    ];
  }
  